__author__ = 'bartoszzasieczny'

urls = (
    '/', 'Index',
    '/landing', 'Landing',
    '/login', 'Login',
    '/reset', 'Reset',
    '/error', 'Error',
    '/create_arrest', 'CreateArrest',
    '/remove_arrest', 'RemoveArrest',
    '/edit_arrest', 'EditArrest',
    '/list_arrests', 'ListArrests',
    '/create_user', 'CreateUser',
    '/edit_user', 'EditUser',
    '/remove_user', 'RemoveUser',
    '/list_users', 'ListUsers',
    '/create_cell', 'CreateCell',
    '/remove_cell', 'RemoveCell',
    '/edit_cell', 'EditCell',
    '/list_cells', 'ListCells',
    '/create_citizen', 'CreateCitizen',
    '/remove_citizen', 'RemoveCitizen',
    '/edit_citizen', 'EditCitizen',
    '/list_citizens', 'ListCitizens',
    '/create_fine', 'CreateFine',
    '/remove_fine', 'RemoveFine',
    '/edit_fine', 'EditFine',
    '/list_fines', 'ListFines',
    '/create_investigation', 'CreateInvestigation',
    '/remove_investigation', 'RemoveInvestigation',
    '/edit_investigation', 'EditInvestigation',
    '/list_investigations', 'ListInvestigations'
)