__author__ = 'bartoszzasieczny'

urls = (
    '/', 'Index',
    '/login', 'Login',
    '/reset', 'Reset',
    '/error', 'Error',
    '/create_arrest', 'CreateArrest',
    '/arrest_created', 'ArrestCreated',
    '/remove_arrest', 'RemoveArrest',
    '/arrest_removed', 'ArrestRemoved',
    '/edit_arrest', 'EditArrest',
    '/arrest_edited', 'ArrestEdited',
    '/list_arrests', 'ListArrests',
    '/create_user', 'CreateUser',
    '/user_created', 'UserCreated',
    '/edit_user', 'EditUser',
    '/user_edited', 'UserEdited',
    '/remove_user', 'RemoveUser',
    '/user_removed', 'UserRemoved',
    '/list_users', 'ListUsers',
    '/create_cell', 'CreateCell',
    '/cell_created', 'CellCreated',
    '/remove_cell', 'RemoveCell',
    '/cell_removed', 'CellRemoved',
    '/edit_cell', 'EditCell',
    '/cell_edited', 'CellEdited',
    '/list_cells', 'ListCells',
    '/create_citizen', 'CreateCitizen',
    '/citizen_created', 'CitizenCreated',
    '/remove_citizen', 'RemoveCitizen',
    '/citizen_removed', 'CitizenRemoved',
    '/edit_citizen', 'EditCitizen',
    '/citizen_edited', 'CitizenEdited',
    '/list_citizens', 'ListCitizens',
    '/create_fine', 'CreateFine',
    '/fine_created', 'FineCreated',
    '/remove_fine', 'RemoveFine',
    '/fine_removed', 'FineRemoved',
    '/edit_fine', 'EditFine',
    '/list_fines', 'ListFines',
    '/create_investigation', 'CreateInvestigation',
    '/remove_investigation', 'RemoveInvestigation',
    '/edit_investigation', 'EditInvestigation',
    '/list_investigations', 'ListInvestigations'
)